a = int(input())
b = int(input())
c = int(input())
arr =[]
arr.append((a+b)+c)
arr.append(a+(b+c))
# arr.append((a+c)+b)
arr.append((a*b)*c)
arr.append(a*(b*c))
# arr.append((a*c)*b)
arr.append((a*b)+c)
# arr.append((a*c)+b)
arr.append((c*b)+a)
arr.append((a+b)*c)
# arr.append((a+c)*b)
arr.append((c+b)*a)
# print(arr)
print(max(arr))
